#!/bin/bash

################################### Parameter Setting ################################

echo "ENCUT convergence test submission initiated"

# Initialize a variable to hold all job IDs.
job_ids=()

# Define the range of ENCUT values to test. For example, from 300 eV to 600 eV.
 # For Ga - ENMAX  =  282.691; ENMIN  =  212.018 eV, for N - ENMAX  =  400.000; ENMIN  =  300.000 eV
 # Usual practice - set ENCUT = largest ENMAX in the POTCAR file	
ENCUT_START=390     # start a bit below the highest ENMAX (here 400 eV) value
ENCUT_END=600       # at least 150% of the highest ENMAX value, here = 600 eV
ENCUT_INCREMENT=20  # increments of 20 to 50 eV are typical choices.

################################### Create directory for each ENCUT value ################################

# Loop over the specified range of ENCUT values.
for (( ENCUT=$ENCUT_START; ENCUT<=$ENCUT_END; ENCUT+=$ENCUT_INCREMENT ))
do
   # Create a directory for the current ENCUT value.
   mkdir ENCUT_${ENCUT}
   cd ENCUT_${ENCUT}

   # Copy VASP input files from the parent directory.
   cp ../INCAR .
   cp ../POSCAR .
   cp ../POTCAR .
   cp ../KPOINTS .

   # Modify the INCAR file to set the ENCUT value.
   sed -i "/^ENCUT/c\ENCUT = $ENCUT" INCAR
