#!/bin/bash

# Define the range of k-points to test. For example, from 4x4x4 to 6x6x6.
K_START=3
K_END=15
K_INCREMENT=2 #choose odd K-mesh grids only

############################### Crate KPOINTS directories #######################################

# Loop over the specified range of k-point values.
for (( K=$K_START; K<=$K_END; K+=$K_INCREMENT ))
do
   # Create a directory for the current k-point grid.
   mkdir KPOINTS_${K}x${K}x${K}
   cd KPOINTS_${K}x${K}x${K}

   # Copy VASP input files from the parent directory.
   cp ../INCAR .
   cp ../POSCAR .
   cp ../POTCAR .

   # Create the KPOINTS file for the current k-point grid.
   echo "Automatic mesh" > KPOINTS
   echo "0" >> KPOINTS
   echo "Gamma" >> KPOINTS
   echo "$K $K $K" >> KPOINTS
